# Generated by Django 3.2.8 on 2021-11-08 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meme', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Index',
            new_name='Post',
        ),
    ]
